export default {
	welcome: 'Welcome on our website!',
	home_msg:
		'Uni-Jas is a place, where you can shop all the necessities for your restaurant, pub or home.',
	enter: 'Enter eshop',
	about: 'About us',
	address: 'Address',
	ico: 'ICO:',
	dic: 'DIC:',
	phone: 'Phone number',
	email: 'E-mail',
	not_logged_in: 'Please log in to continue shopping.',
	basket_empty: 'Your basket is empty, please add some products first.',
	g_total: 'Grand Total:',
	checkout: 'Checkout',
	delivery_addr: 'Delivery address',
	payment: 'Payment method',
	confirm_order: 'Confirm order',
	not_found: 'Not Found',
	not_found_msg: 'Oops, looks like this page does not exist',
	product_added: 'Product was added to the basket',
	product_not_exist: 'Product does not exist.',
	product_removed: 'Product was removed from the basket',
	no_products: 'No products in your basket yet.',
	sign_in: 'Sign in',
	log_in: 'LogIn',
	signup: 'SignUp',
	login: 'Login',
	basket: 'Basket',
	slovakia: 'Slovakia',
	home: 'Home',
	products: 'Products',
	entity: 'pcs',
	amount: 'Amount: ',
	total: 'Total: ',
	stored_addr: 'Stored address',
	custom_addr: 'Custom address',
	street: 'Street',
	number: 'Number',
	city: 'City',
	postal_code: 'Postal Code',
	credit_card: 'Credit card',
	transfer: 'Bank transfer',
	cash: 'Cash on delivery',
	add: 'Add to basket',
	basket_label: 'Shopping basket',
	pwd: 'Password',
	en: 'English',
	sk: 'Slovak'
};
