export default {
	welcome: 'Vitajte na našej stánke!',
	home_msg:
		'Uni-Jas je miesto, kde nakúpite všetky potrebné veci pre Vašu reštauráciu, bar alebo domov.',
	enter: 'Vstúpte do eshopu',
	about: 'O nás',
	address: 'Adresa',
	ico: 'IČO:',
	dic: 'DIČ:',
	phone: 'Telefónne číslo:',
	email: 'E-mail:',
	not_logged_in: 'Prosím prihláste sa pre pokračovanie.',
	basket_empty: 'Váš košík je prázdny, prosím pridajte produkty.',
	g_total: 'Celkový suma:',
	checkout: 'K pokladni',
	delivery_addr: 'Dodacia adresa',
	payment: 'Typ platby',
	confirm_order: 'Potvrdiť objednávku',
	not_found: 'Nič nebolo nájdené',
	not_found_msg: 'Bohužial, táto stránka neexistuje',
	product_added: 'Produkt bol pridaný do košíka',
	product_not_exist: 'Produkt neexistuje.',
	product_removed: 'Produkt bol odobraný z košíka',
	no_products: 'V košíku sa nenachádzajú žiadne produkty.',
	sign_in: 'Registrovať sa',
	log_in: 'Prihlásiť sa',
	signup: 'Registrovať sa',
	login: 'Prihlásiť sa',
	basket: 'Košík',
	slovakia: 'Slovensko',
	home: 'Domov',
	products: 'Produkty',
	entity: 'ks',
	amount: 'Suma: ',
	total: 'Celkovo: ',
	stored_addr: 'Uložená adresa',
	custom_addr: 'Iná adresa',
	street: 'Ulica',
	number: 'Číslo',
	city: 'Mesto',
	postal_code: 'PSČ',
	credit_card: 'Kreditná karta',
	transfer: 'Bankový prevod',
	cash: 'Platba v hotovosti',
	add: 'Pridať do košíka',
	basket_label: 'Košík',
	pwd: 'Heslo',
	en: 'Angličtina',
	sk: 'Slovenčina',
	product: 'Produkt detail',
	prices_info: 'Prosím, prihláste sa pre zobrazenie ceny'
};
